linux:
  - 'src/**'
  - 'rustutils/**'
  - 'test/**'
  - 'render-test/**'
  - 'expression-test/**'
  - 'include/**'
  - '.github/workflows/linux-ci.yml'
  - 'vendor/**'
  - 'CMakeLists.txt'
  - 'metrics/linux-gcc8-release-style.json'
  - 'MODULE.bazel'
  - 'BUILD.bazel'
  - '.bazelrc'
  - '.bazelversion'
  - '.bazelignore'
  - '!**/*.md'
windows:
  - '.github/workflows/windows-ci.yml'
  - 'src/**'
  - 'include/**'
  - 'platform/default/**'
  - 'platform/windows/**'
  - 'expression-test/**'
  - 'render-test/**'
  - 'test/**'
  - 'metrics/**'
  - 'vendor/**'
  - '.gitmodules'
  - '!**/*.md'
ios:
  - 'platform/ios/**'
  - 'platform/darwin/**'
  - '.github/workflows/ios-ci.yml'
  - 'bin/**'
  - 'expression-test/**'
  - 'include/**'
  - 'metrics/**'
  - 'platform/default/**'
  - 'render-test/**'
  - 'scripts/**'
  - 'src/**'
  - 'test/**'
  - 'vendor/**'
  - '.gitmodules'
  - 'MODULE.bazel'
  - 'BUILD.bazel'
  - '.bazelrc'
  - '.bazelversion'
  - '.bazelignore'
  - 'pnpm-lock.yaml'
  - '!**/*.md'
android:
  - 'CMakeLists.txt'
  - 'platform/android/**'
  - '.github/workflows/android-ci.yml'
  - 'bin/**'
  - 'expression-test/**'
  - 'include/**'
  - 'metrics/**'
  - 'platform/default/**'
  - 'render-test/**'
  - 'scripts/**'
  - 'src/**'
  - 'test/**'
  - 'vendor/**'
  - '.gitmodules'
  - '!**/*.md'
