linux:
  - 'src/**'
  - 'test/**'
  - 'render-test/**'
  - 'expression-test/**'
  - 'include/**'
  - '.github/workflows/linux-ci.yml'
  - 'vendor/**'
  - 'CMakeLists.txt'
  - 'metrics/linux-gcc8-release-style.json'
  - 'WORKSPACE'
  - 'BUILD.bazel'
  - '.bazelrc'
  - '.bazelversion'
ios:
  - 'platform/ios/**'
  - 'platform/darwin/**'
  - '.github/workflows/ios-ci.yml'
  - 'bin/**'
  - 'expression-test/**'
  - 'include/**'
  - 'metrics/**'
  - 'platform/default/**'
  - 'render-test/**'
  - 'scripts/**'
  - 'src/**'
  - 'test/**'
  - 'vendor/**'
  - '.gitmodules'
  - '!**/*.md'
  - 'WORKSPACE'
  - 'BUILD.bazel'
  - '.bazelrc'
  - '.bazelversion'
  - 'pnpm-lock.yaml'
android:
  - 'CMakeLists.txt'
  - 'platform/android/**'
  - '.github/workflows/android-ci.yml'
  - 'bin/**'
  - 'expression-test/**'
  - 'include/**'
  - 'metrics/**'
  - 'platform/default/**'
  - 'render-test/**'
  - 'scripts/**'
  - 'src/**'
  - 'test/**'
  - 'vendor/**'
  - '.gitmodules'
  - '!**/*.md'