#!/usr/bin/bash

sudo apt-get update
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
  libcurl4-openssl-dev \
  libuv1-dev \
  libjpeg-dev \
  libpng-dev \
  libglfw3-dev \
  libwebp-dev \
  libopengl0 \
  mesa-vulkan-drivers
cargo install armerge@2.2.0
