execute_process(COMMAND xcrun --sdk macosx --show-sdk-path OUTPUT_VARIABLE _MAC_SDK OUTPUT_STRIP_TRAILING_WHITESPACE)
set(CMAKE_OSX_SYSROOT "${_MAC_SDK}" CACHE PATH "macOS SDK for Mac Catalyst" FORCE)
set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_VERSION 14.0)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_OSX_DEPLOYMENT_TARGET 14.0 CACHE STRING "Catalyst deployment target" FORCE)
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "Catalyst arch" FORCE)
foreach(lang C CXX OBJC OBJCXX)
    set(CMAKE_${lang}_FLAGS_INIT "-target arm64-apple-ios14.0-macabi")
endforeach()
set(MLN_MAC_CATALYST ON CACHE BOOL "Build for Mac Catalyst" FORCE)
