site_name: MapLibre Android Examples
site_url: https://www.maplibre.org/maplibre-style-spec/
repo_url: https://github.com/maplibre/maplibre-style-spec
site_description: Documentation for the MapLibre Style Specification
extra_css:
  - assets/extra.css
theme:
  name: 'material'
  favicon: https://maplibre.org/favicon.ico
  logo: assets/logo.svg
  features:
    - content.code.copy
    # - toc.follow
    - search.suggest
    # - navigation.instant
    # - navigation.sections
    - navigation.top  # back to top button
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@maplibre
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/maplibre
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/maplibre
    - icon: fontawesome/brands/slack
      link: https://osmus.slack.com/archives/C01G3D28DAB
    - icon: fontawesome/brands/github
      link: https://github.com/maplibre
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: '#295DAA'
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
