name: setup-android-ci
description: "Sets up Android CI environment"
runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      if: startsWith(runner.name, 'GitHub Actions')
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: false
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: false

    - name: Validate VERSION
      run: .github/scripts/validate-version.sh platform/android/VERSION
      working-directory: .
      shell: bash

    - run: echo "cmake.dir=$(dirname "$(dirname "$(command -v cmake)")")" >> local.properties
      shell: bash

    - uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Get CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.24.1
        ninjaVersion: latest

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - name: npm install
      run: npm install --ignore-scripts
      working-directory: .
      shell: bash

    - name: run platform/android/scripts/generate-style-code.mjs
      run: node platform/android/scripts/generate-style-code.mjs
      working-directory: .
      shell: bash

    - run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install pre-commit
      shell: bash

    - run: |
        source venv/bin/activate
        pre-commit run clang-format --all-files
      continue-on-error: true # this can mean files are modified, which is not an error
      shell: bash

    - run: |
        source venv/bin/activate
        pre-commit run clang-format --all-files
        rm -rf venv
      shell: bash

    - uses: infotroph/tree-is-clean@v1
      with:
        check_untracked: true

    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}
        append-timestamp: false
        max-size: 5G

    - name: restore-gradle-cache
      uses: actions/cache@v4
      env:
        cache-name: gradle-v1
      with:
        path: ~/.gradle
        key: ${{ env.cache-name }}-${{ hashFiles('platform/android/buildSrc/src/main/kotlin/maplibre.dependencies.gradle.kts') }}-${{ hashFiles('platform/android/build.gradle.kts') }}-${{ hashFiles('platform/android/local.properties') }}-${{ hashFiles('platform/android/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          - ${{ env.cache-name }}
