// Generated code, do not modify this file!
#include <mbgl/shaders/shader_source.hpp>
#include <mbgl/util/enum.hpp>

namespace mbgl {

using namespace shaders;

MBGL_DEFINE_ENUM(BuiltIn,
                 {{BuiltIn::None, "None"},
                  {BuiltIn::BackgroundShader, "BackgroundShader"},
                  {BuiltIn::BackgroundPatternShader, "BackgroundPatternShader"},
                  {BuiltIn::CircleShader, "CircleShader"},
                  {BuiltIn::CollisionBoxShader, "CollisionBoxShader"},
                  {BuiltIn::CollisionCircleShader, "CollisionCircleShader"},
                  {BuiltIn::CustomGeometryShader, "CustomGeometryShader"},
                  {BuiltIn::CustomSymbolIconShader, "CustomSymbolIconShader"},
                  {BuiltIn::DebugShader, "DebugShader"},
                  {BuiltIn::FillShader, "FillShader"},
                  {BuiltIn::FillOutlineShader, "FillOutlineShader"},
                  {BuiltIn::FillPatternShader, "FillPatternShader"},
                  {BuiltIn::FillOutlinePatternShader, "FillOutlinePatternShader"},
                  {BuiltIn::FillOutlineTriangulatedShader, "FillOutlineTriangulatedShader"},
                  {BuiltIn::FillExtrusionShader, "FillExtrusionShader"},
                  {BuiltIn::FillExtrusionPatternShader, "FillExtrusionPatternShader"},
                  {BuiltIn::HeatmapShader, "HeatmapShader"},
                  {BuiltIn::HeatmapTextureShader, "HeatmapTextureShader"},
                  {BuiltIn::HillshadePrepareShader, "HillshadePrepareShader"},
                  {BuiltIn::HillshadeShader, "HillshadeShader"},
                  {BuiltIn::LineShader, "LineShader"},
                  {BuiltIn::LineGradientShader, "LineGradientShader"},
                  {BuiltIn::LinePatternShader, "LinePatternShader"},
                  {BuiltIn::LocationIndicatorShader, "LocationIndicatorShader"},
                  {BuiltIn::LocationIndicatorTexturedShader, "LocationIndicatorTexturedShader"},
                  {BuiltIn::LineSDFShader, "LineSDFShader"},
                  {BuiltIn::RasterShader, "RasterShader"},
                  {BuiltIn::SymbolIconShader, "SymbolIconShader"},
                  {BuiltIn::SymbolSDFIconShader, "SymbolSDFIconShader"},
                  {BuiltIn::SymbolTextAndIconShader, "SymbolTextAndIconShader"},
                  {BuiltIn::WideVectorShader, "WideVectorShader"},
                  {BuiltIn::Prelude, "Prelude"},
                  {BuiltIn::BackgroundProgram, "BackgroundProgram"},
                  {BuiltIn::BackgroundPatternProgram, "BackgroundPatternProgram"},
                  {BuiltIn::CircleProgram, "CircleProgram"},
                  {BuiltIn::ClippingMaskProgram, "ClippingMaskProgram"},
                  {BuiltIn::CollisionBoxProgram, "CollisionBoxProgram"},
                  {BuiltIn::CollisionCircleProgram, "CollisionCircleProgram"},
                  {BuiltIn::DebugProgram, "DebugProgram"},
                  {BuiltIn::FillExtrusionPatternProgram, "FillExtrusionPatternProgram"},
                  {BuiltIn::FillExtrusionProgram, "FillExtrusionProgram"},
                  {BuiltIn::FillOutlinePatternProgram, "FillOutlinePatternProgram"},
                  {BuiltIn::FillOutlineProgram, "FillOutlineProgram"},
                  {BuiltIn::FillPatternProgram, "FillPatternProgram"},
                  {BuiltIn::FillProgram, "FillProgram"},
                  {BuiltIn::HeatmapTextureProgram, "HeatmapTextureProgram"},
                  {BuiltIn::HeatmapProgram, "HeatmapProgram"},
                  {BuiltIn::HillshadePrepareProgram, "HillshadePrepareProgram"},
                  {BuiltIn::HillshadeProgram, "HillshadeProgram"},
                  {BuiltIn::LineGradientProgram, "LineGradientProgram"},
                  {BuiltIn::LinePatternProgram, "LinePatternProgram"},
                  {BuiltIn::LineSDFProgram, "LineSDFProgram"},
                  {BuiltIn::LineProgram, "LineProgram"},
                  {BuiltIn::RasterProgram, "RasterProgram"},
                  {BuiltIn::SymbolIconProgram, "SymbolIconProgram"},
                  {BuiltIn::SymbolSDFTextProgram, "SymbolSDFTextProgram"},
                  {BuiltIn::SymbolSDFIconProgram, "SymbolSDFIconProgram"},
                  {BuiltIn::SymbolTextAndIconProgram, "SymbolTextAndIconProgram"}});

} // namespace mbgl
