// Generated by scripts/generate-shaders.mjs. Do not edit by hand.
// clang-format off
#pragma once

inline constexpr char openglVertex[] = R"SHADER(
in vec2 a_position;
#if !MLN_PLUGIN_PROPERTY_NGON_RADIUS_IS_UNIFORM
in vec2 a_radius;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_CORNERS_IS_UNIFORM
in vec2 a_corners;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_ROTATE_IS_UNIFORM
in vec2 a_rotate;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_COLOR_IS_UNIFORM
in vec4 a_color_min;
in vec4 a_color_max;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_BLUR_IS_UNIFORM
in vec2 a_blur;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_OPACITY_IS_UNIFORM
in vec2 a_opacity;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_WIDTH_IS_UNIFORM
in vec2 a_stroke_width;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_COLOR_IS_UNIFORM
in vec4 a_stroke_color_min;
in vec4 a_stroke_color_max;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_OPACITY_IS_UNIFORM
in vec2 a_stroke_opacity;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_IS_UNIFORM
in vec4 a_translate;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_ANCHOR_IS_UNIFORM
in vec2 a_translate_anchor;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_ALIGNMENT_IS_UNIFORM
in vec2 a_pitch_alignment;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_SCALE_IS_UNIFORM
in vec2 a_pitch_scale;
#endif

layout(std140) uniform NgonDrawableUBO {
    mat4 matrix;
    vec4 camera;
    vec4 view;
    float radius;
    float corners;
    float rotate;
    float blur;
    float opacity;
    float stroke_width;
    float stroke_opacity;
    float translate_anchor;
    vec4 color;
    vec4 stroke_color;
    vec2 translate;
    float pitch_alignment;
    float pitch_scale;
    vec4 interpolation0;
    vec4 interpolation1;
    vec4 interpolation2;
    vec4 interpolation3;
} u;
out vec2 v_local;
out vec4 v_shape;
out vec4 v_paint;
out vec4 v_color;
out vec4 v_stroke_color;

void main() {
    float radius = u.radius;
#if !MLN_PLUGIN_PROPERTY_NGON_RADIUS_IS_UNIFORM
    radius = mix(a_radius.x, a_radius.y, u.interpolation0.x);
#endif
    float corners = u.corners;
#if !MLN_PLUGIN_PROPERTY_NGON_CORNERS_IS_UNIFORM
    corners = mix(a_corners.x, a_corners.y, u.interpolation0.y);
#endif
    float rotate = u.rotate;
#if !MLN_PLUGIN_PROPERTY_NGON_ROTATE_IS_UNIFORM
    rotate = mix(a_rotate.x, a_rotate.y, u.interpolation0.z);
#endif
    vec4 color = u.color;
#if !MLN_PLUGIN_PROPERTY_NGON_COLOR_IS_UNIFORM
    color = mix(a_color_min, a_color_max, u.interpolation0.w);
#endif
    float blur = u.blur;
#if !MLN_PLUGIN_PROPERTY_NGON_BLUR_IS_UNIFORM
    blur = mix(a_blur.x, a_blur.y, u.interpolation1.x);
#endif
    float opacity = u.opacity;
#if !MLN_PLUGIN_PROPERTY_NGON_OPACITY_IS_UNIFORM
    opacity = mix(a_opacity.x, a_opacity.y, u.interpolation1.y);
#endif
    float stroke_width = u.stroke_width;
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_WIDTH_IS_UNIFORM
    stroke_width = mix(a_stroke_width.x, a_stroke_width.y, u.interpolation1.z);
#endif
    vec4 stroke_color = u.stroke_color;
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_COLOR_IS_UNIFORM
    stroke_color = mix(a_stroke_color_min, a_stroke_color_max, u.interpolation1.w);
#endif
    float stroke_opacity = u.stroke_opacity;
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_OPACITY_IS_UNIFORM
    stroke_opacity = mix(a_stroke_opacity.x, a_stroke_opacity.y, u.interpolation2.x);
#endif
    vec2 translate = u.translate;
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_IS_UNIFORM
    translate = mix(a_translate.xy, a_translate.zw, u.interpolation2.y);
#endif
    float translate_anchor = u.translate_anchor;
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_ANCHOR_IS_UNIFORM
    translate_anchor = u.interpolation2.z < 1.0 ? a_translate_anchor.x : a_translate_anchor.y;
#endif
    float pitch_alignment = u.pitch_alignment;
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_ALIGNMENT_IS_UNIFORM
    pitch_alignment = u.interpolation2.w < 1.0 ? a_pitch_alignment.x : a_pitch_alignment.y;
#endif
    float pitch_scale = u.pitch_scale;
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_SCALE_IS_UNIFORM
    pitch_scale = u.interpolation3.x < 1.0 ? a_pitch_scale.x : a_pitch_scale.y;
#endif

    radius = max(radius, 0.0);
    stroke_width = max(stroke_width, 0.0);
    corners = clamp(floor(corners + 0.5), 3.0, 360.0);
    vec2 encoded = vec2(a_position);
    vec2 center = floor(encoded * 0.5);
    vec2 corner = encoded - 2.0 * center;
    corner = corner * 2.0 - 1.0;
    if (translate_anchor > 0.5) {
        float c = cos(-u.view.x), s = sin(-u.view.x);
        translate = vec2(c * translate.x - s * translate.y, s * translate.x + c * translate.y);
    }
    center += translate * u.camera.z;
    vec4 projected = u.matrix * vec4(center, 0.0, 1.0);
    float outer_radius = radius + stroke_width / cos(3.141592653589793 / corners);
    float extent = outer_radius + 2.0 / max(u.view.y, 1.0);
    vec2 local = corner * extent;
    vec4 position;
    if (pitch_alignment < 0.5) {
        vec2 offset = local * u.camera.z;
        if (pitch_scale > 0.5) offset *= projected.w / u.camera.w;
        position = u.matrix * vec4(center + offset, 0.0, 1.0);
    } else {
        float scale = pitch_scale < 0.5 ? u.camera.w : projected.w;
        position = projected + vec4(local * u.camera.xy * scale, 0.0, 0.0);
    }
    v_local = local;
    v_shape = vec4(radius, stroke_width, corners, rotate * 0.017453292519943295);
    v_paint = vec4(clamp(blur, 0.0, 1.0), clamp(opacity, 0.0, 1.0), clamp(stroke_opacity, 0.0, 1.0), 0.0);
    v_color = color;
    v_stroke_color = stroke_color;
    gl_Position = position;
}
)SHADER";

inline constexpr char openglFragment[] = R"SHADER(
in vec2 v_local;
in vec4 v_shape;
in vec4 v_paint;
in vec4 v_color;
in vec4 v_stroke_color;

void main() {

    float radius = v_shape.x;
    float stroke = v_shape.y;
    float sector = 6.283185307179586 / v_shape.z;
    float angle = (length(v_local) > 0.0 ? atan(v_local.y, v_local.x) : 0.0) + 1.5707963267948966 - v_shape.w;
    float edge = floor(angle / sector) * sector + sector * 0.5;
    float support = cos(angle - edge) * length(v_local);
    float inner_distance = radius * cos(sector * 0.5) - support;
    float aa = max(fwidth(support) * 0.5, 0.0001);
    float outer = smoothstep(-aa, max(aa, v_paint.x * radius), inner_distance + stroke);
    float fill = stroke > 0.0 ? smoothstep(-aa, aa, inner_distance) : 1.0;
    vec4 result = mix(v_stroke_color * v_paint.z, v_color * v_paint.y, fill) * outer;
    if (radius + stroke <= 0.0) result = vec4(0.0);
    fragColor = result;
}
)SHADER";

inline constexpr char vulkanVertex[] = R"SHADER(
layout(location = 0) in ivec2 a_position;
#if !MLN_PLUGIN_PROPERTY_NGON_RADIUS_IS_UNIFORM
layout(location = 1) in vec2 a_radius;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_CORNERS_IS_UNIFORM
layout(location = 2) in vec2 a_corners;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_ROTATE_IS_UNIFORM
layout(location = 3) in vec2 a_rotate;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_COLOR_IS_UNIFORM
layout(location = 4) in vec4 a_color_min;
layout(location = 5) in vec4 a_color_max;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_BLUR_IS_UNIFORM
layout(location = 6) in vec2 a_blur;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_OPACITY_IS_UNIFORM
layout(location = 7) in vec2 a_opacity;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_WIDTH_IS_UNIFORM
layout(location = 8) in vec2 a_stroke_width;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_COLOR_IS_UNIFORM
layout(location = 9) in vec4 a_stroke_color_min;
layout(location = 10) in vec4 a_stroke_color_max;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_OPACITY_IS_UNIFORM
layout(location = 11) in vec2 a_stroke_opacity;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_IS_UNIFORM
layout(location = 12) in vec4 a_translate;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_ANCHOR_IS_UNIFORM
layout(location = 13) in vec2 a_translate_anchor;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_ALIGNMENT_IS_UNIFORM
layout(location = 14) in vec2 a_pitch_alignment;
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_SCALE_IS_UNIFORM
layout(location = 15) in vec2 a_pitch_scale;
#endif

layout(std140, set = DRAWABLE_UBO_SET_INDEX, binding = MLN_PLUGIN_UNIFORM_0_BINDING) uniform NgonDrawableUBO {
    mat4 matrix;
    vec4 camera;
    vec4 view;
    float radius;
    float corners;
    float rotate;
    float blur;
    float opacity;
    float stroke_width;
    float stroke_opacity;
    float translate_anchor;
    vec4 color;
    vec4 stroke_color;
    vec2 translate;
    float pitch_alignment;
    float pitch_scale;
    vec4 interpolation0;
    vec4 interpolation1;
    vec4 interpolation2;
    vec4 interpolation3;
} u;
layout(location = 0) out vec2 v_local;
layout(location = 1) out vec4 v_shape;
layout(location = 2) out vec4 v_paint;
layout(location = 3) out vec4 v_color;
layout(location = 4) out vec4 v_stroke_color;

void main() {
    float radius = u.radius;
#if !MLN_PLUGIN_PROPERTY_NGON_RADIUS_IS_UNIFORM
    radius = mix(a_radius.x, a_radius.y, u.interpolation0.x);
#endif
    float corners = u.corners;
#if !MLN_PLUGIN_PROPERTY_NGON_CORNERS_IS_UNIFORM
    corners = mix(a_corners.x, a_corners.y, u.interpolation0.y);
#endif
    float rotate = u.rotate;
#if !MLN_PLUGIN_PROPERTY_NGON_ROTATE_IS_UNIFORM
    rotate = mix(a_rotate.x, a_rotate.y, u.interpolation0.z);
#endif
    vec4 color = u.color;
#if !MLN_PLUGIN_PROPERTY_NGON_COLOR_IS_UNIFORM
    color = mix(a_color_min, a_color_max, u.interpolation0.w);
#endif
    float blur = u.blur;
#if !MLN_PLUGIN_PROPERTY_NGON_BLUR_IS_UNIFORM
    blur = mix(a_blur.x, a_blur.y, u.interpolation1.x);
#endif
    float opacity = u.opacity;
#if !MLN_PLUGIN_PROPERTY_NGON_OPACITY_IS_UNIFORM
    opacity = mix(a_opacity.x, a_opacity.y, u.interpolation1.y);
#endif
    float stroke_width = u.stroke_width;
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_WIDTH_IS_UNIFORM
    stroke_width = mix(a_stroke_width.x, a_stroke_width.y, u.interpolation1.z);
#endif
    vec4 stroke_color = u.stroke_color;
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_COLOR_IS_UNIFORM
    stroke_color = mix(a_stroke_color_min, a_stroke_color_max, u.interpolation1.w);
#endif
    float stroke_opacity = u.stroke_opacity;
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_OPACITY_IS_UNIFORM
    stroke_opacity = mix(a_stroke_opacity.x, a_stroke_opacity.y, u.interpolation2.x);
#endif
    vec2 translate = u.translate;
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_IS_UNIFORM
    translate = mix(a_translate.xy, a_translate.zw, u.interpolation2.y);
#endif
    float translate_anchor = u.translate_anchor;
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_ANCHOR_IS_UNIFORM
    translate_anchor = u.interpolation2.z < 1.0 ? a_translate_anchor.x : a_translate_anchor.y;
#endif
    float pitch_alignment = u.pitch_alignment;
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_ALIGNMENT_IS_UNIFORM
    pitch_alignment = u.interpolation2.w < 1.0 ? a_pitch_alignment.x : a_pitch_alignment.y;
#endif
    float pitch_scale = u.pitch_scale;
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_SCALE_IS_UNIFORM
    pitch_scale = u.interpolation3.x < 1.0 ? a_pitch_scale.x : a_pitch_scale.y;
#endif

    radius = max(radius, 0.0);
    stroke_width = max(stroke_width, 0.0);
    corners = clamp(floor(corners + 0.5), 3.0, 360.0);
    vec2 encoded = vec2(a_position);
    vec2 center = floor(encoded * 0.5);
    vec2 corner = encoded - 2.0 * center;
    corner = corner * 2.0 - 1.0;
    if (translate_anchor > 0.5) {
        float c = cos(-u.view.x), s = sin(-u.view.x);
        translate = vec2(c * translate.x - s * translate.y, s * translate.x + c * translate.y);
    }
    center += translate * u.camera.z;
    vec4 projected = u.matrix * vec4(center, 0.0, 1.0);
    float outer_radius = radius + stroke_width / cos(3.141592653589793 / corners);
    float extent = outer_radius + 2.0 / max(u.view.y, 1.0);
    vec2 local = corner * extent;
    vec4 position;
    if (pitch_alignment < 0.5) {
        vec2 offset = local * u.camera.z;
        if (pitch_scale > 0.5) offset *= projected.w / u.camera.w;
        position = u.matrix * vec4(center + offset, 0.0, 1.0);
    } else {
        float scale = pitch_scale < 0.5 ? u.camera.w : projected.w;
        position = projected + vec4(local * u.camera.xy * scale, 0.0, 0.0);
    }
    v_local = local;
    v_shape = vec4(radius, stroke_width, corners, rotate * 0.017453292519943295);
    v_paint = vec4(clamp(blur, 0.0, 1.0), clamp(opacity, 0.0, 1.0), clamp(stroke_opacity, 0.0, 1.0), 0.0);
    v_color = color;
    v_stroke_color = stroke_color;
    gl_Position = position;
    applySurfaceTransform();
}
)SHADER";

inline constexpr char vulkanFragment[] = R"SHADER(
layout(location = 0) in vec2 v_local;
layout(location = 1) in vec4 v_shape;
layout(location = 2) in vec4 v_paint;
layout(location = 3) in vec4 v_color;
layout(location = 4) in vec4 v_stroke_color;
layout(location = 0) out vec4 fragColor;

void main() {

    float radius = v_shape.x;
    float stroke = v_shape.y;
    float sector = 6.283185307179586 / v_shape.z;
    float angle = (length(v_local) > 0.0 ? atan(v_local.y, v_local.x) : 0.0) + 1.5707963267948966 - v_shape.w;
    float edge = floor(angle / sector) * sector + sector * 0.5;
    float support = cos(angle - edge) * length(v_local);
    float inner_distance = radius * cos(sector * 0.5) - support;
    float aa = max(fwidth(support) * 0.5, 0.0001);
    float outer = smoothstep(-aa, max(aa, v_paint.x * radius), inner_distance + stroke);
    float fill = stroke > 0.0 ? smoothstep(-aa, aa, inner_distance) : 1.0;
    vec4 result = mix(v_stroke_color * v_paint.z, v_color * v_paint.y, fill) * outer;
    if (radius + stroke <= 0.0) result = vec4(0.0);
    fragColor = result;
}
)SHADER";

inline constexpr char metalSource[] = R"SHADER(
struct alignas(16) NgonDrawableUBO {
    float4x4 matrix;
    float4 camera;
    float4 view;
    float radius;
    float corners;
    float rotate;
    float blur;
    float opacity;
    float stroke_width;
    float stroke_opacity;
    float translate_anchor;
    float4 color;
    float4 stroke_color;
    float2 translate;
    float pitch_alignment;
    float pitch_scale;
    float4 interpolation0;
    float4 interpolation1;
    float4 interpolation2;
    float4 interpolation3;
};
struct NgonVertex {
    short2 a_position [[attribute(0)]];
#if !MLN_PLUGIN_PROPERTY_NGON_RADIUS_IS_UNIFORM
    float2 a_radius [[attribute(1)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_CORNERS_IS_UNIFORM
    float2 a_corners [[attribute(2)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_ROTATE_IS_UNIFORM
    float2 a_rotate [[attribute(3)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_COLOR_IS_UNIFORM
    float4 a_color_min [[attribute(4)]];
    float4 a_color_max [[attribute(5)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_BLUR_IS_UNIFORM
    float2 a_blur [[attribute(6)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_OPACITY_IS_UNIFORM
    float2 a_opacity [[attribute(7)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_WIDTH_IS_UNIFORM
    float2 a_stroke_width [[attribute(8)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_COLOR_IS_UNIFORM
    float4 a_stroke_color_min [[attribute(9)]];
    float4 a_stroke_color_max [[attribute(10)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_OPACITY_IS_UNIFORM
    float2 a_stroke_opacity [[attribute(11)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_IS_UNIFORM
    float4 a_translate [[attribute(12)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_ANCHOR_IS_UNIFORM
    float2 a_translate_anchor [[attribute(13)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_ALIGNMENT_IS_UNIFORM
    float2 a_pitch_alignment [[attribute(14)]];
#endif
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_SCALE_IS_UNIFORM
    float2 a_pitch_scale [[attribute(15)]];
#endif
};
struct NgonVaryings {
    float4 position [[position]];
    float2 local;
    float4 shape;
    float4 paint;
    float4 color;
    float4 stroke_color;
};
vertex NgonVaryings ngonVertex(NgonVertex in [[stage_in]],
    constant NgonDrawableUBO& u [[buffer(MLN_PLUGIN_UNIFORM_0_BINDING)]]) {
    NgonVaryings out;
    float radius = u.radius;
#if !MLN_PLUGIN_PROPERTY_NGON_RADIUS_IS_UNIFORM
    radius = mix(in.a_radius.x, in.a_radius.y, u.interpolation0.x);
#endif
    float corners = u.corners;
#if !MLN_PLUGIN_PROPERTY_NGON_CORNERS_IS_UNIFORM
    corners = mix(in.a_corners.x, in.a_corners.y, u.interpolation0.y);
#endif
    float rotate = u.rotate;
#if !MLN_PLUGIN_PROPERTY_NGON_ROTATE_IS_UNIFORM
    rotate = mix(in.a_rotate.x, in.a_rotate.y, u.interpolation0.z);
#endif
    float4 color = u.color;
#if !MLN_PLUGIN_PROPERTY_NGON_COLOR_IS_UNIFORM
    color = mix(in.a_color_min, in.a_color_max, u.interpolation0.w);
#endif
    float blur = u.blur;
#if !MLN_PLUGIN_PROPERTY_NGON_BLUR_IS_UNIFORM
    blur = mix(in.a_blur.x, in.a_blur.y, u.interpolation1.x);
#endif
    float opacity = u.opacity;
#if !MLN_PLUGIN_PROPERTY_NGON_OPACITY_IS_UNIFORM
    opacity = mix(in.a_opacity.x, in.a_opacity.y, u.interpolation1.y);
#endif
    float stroke_width = u.stroke_width;
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_WIDTH_IS_UNIFORM
    stroke_width = mix(in.a_stroke_width.x, in.a_stroke_width.y, u.interpolation1.z);
#endif
    float4 stroke_color = u.stroke_color;
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_COLOR_IS_UNIFORM
    stroke_color = mix(in.a_stroke_color_min, in.a_stroke_color_max, u.interpolation1.w);
#endif
    float stroke_opacity = u.stroke_opacity;
#if !MLN_PLUGIN_PROPERTY_NGON_STROKE_OPACITY_IS_UNIFORM
    stroke_opacity = mix(in.a_stroke_opacity.x, in.a_stroke_opacity.y, u.interpolation2.x);
#endif
    float2 translate = u.translate;
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_IS_UNIFORM
    translate = mix(in.a_translate.xy, in.a_translate.zw, u.interpolation2.y);
#endif
    float translate_anchor = u.translate_anchor;
#if !MLN_PLUGIN_PROPERTY_NGON_TRANSLATE_ANCHOR_IS_UNIFORM
    translate_anchor = u.interpolation2.z < 1.0 ? in.a_translate_anchor.x : in.a_translate_anchor.y;
#endif
    float pitch_alignment = u.pitch_alignment;
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_ALIGNMENT_IS_UNIFORM
    pitch_alignment = u.interpolation2.w < 1.0 ? in.a_pitch_alignment.x : in.a_pitch_alignment.y;
#endif
    float pitch_scale = u.pitch_scale;
#if !MLN_PLUGIN_PROPERTY_NGON_PITCH_SCALE_IS_UNIFORM
    pitch_scale = u.interpolation3.x < 1.0 ? in.a_pitch_scale.x : in.a_pitch_scale.y;
#endif

    radius = max(radius, 0.0);
    stroke_width = max(stroke_width, 0.0);
    corners = clamp(floor(corners + 0.5), 3.0, 360.0);
    float2 encoded = float2(in.a_position);
    float2 center = floor(encoded * 0.5);
    float2 corner = encoded - 2.0 * center;
    corner = corner * 2.0 - 1.0;
    if (translate_anchor > 0.5) {
        float c = cos(-u.view.x), s = sin(-u.view.x);
        translate = float2(c * translate.x - s * translate.y, s * translate.x + c * translate.y);
    }
    center += translate * u.camera.z;
    float4 projected = u.matrix * float4(center, 0.0, 1.0);
    float outer_radius = radius + stroke_width / cos(3.141592653589793 / corners);
    float extent = outer_radius + 2.0 / max(u.view.y, 1.0);
    float2 local = corner * extent;
    float4 position;
    if (pitch_alignment < 0.5) {
        float2 offset = local * u.camera.z;
        if (pitch_scale > 0.5) offset *= projected.w / u.camera.w;
        position = u.matrix * float4(center + offset, 0.0, 1.0);
    } else {
        float scale = pitch_scale < 0.5 ? u.camera.w : projected.w;
        position = projected + float4(local * u.camera.xy * scale, 0.0, 0.0);
    }
    out.local = local;
    out.shape = float4(radius, stroke_width, corners, rotate * 0.017453292519943295);
    out.paint = float4(clamp(blur, 0.0, 1.0), clamp(opacity, 0.0, 1.0), clamp(stroke_opacity, 0.0, 1.0), 0.0);
    out.color = color;
    out.stroke_color = stroke_color;
    out.position = position;
    return out;
}
fragment half4 ngonFragment(NgonVaryings in [[stage_in]]) {

    float radius = in.shape.x;
    float stroke = in.shape.y;
    float sector = 6.283185307179586 / in.shape.z;
    float angle = (length(in.local) > 0.0 ? atan2(in.local.y, in.local.x) : 0.0) + 1.5707963267948966 - in.shape.w;
    float edge = floor(angle / sector) * sector + sector * 0.5;
    float support = cos(angle - edge) * length(in.local);
    float inner_distance = radius * cos(sector * 0.5) - support;
    float aa = max(fwidth(support) * 0.5, 0.0001);
    float outer = smoothstep(-aa, max(aa, in.paint.x * radius), inner_distance + stroke);
    float fill = stroke > 0.0 ? smoothstep(-aa, aa, inner_distance) : 1.0;
    float4 result = mix(in.stroke_color * in.paint.z, in.color * in.paint.y, fill) * outer;
    if (radius + stroke <= 0.0) result = float4(0.0);
    return half4(result);
}
)SHADER";

const mln_plugin_shader_attribute_v1 shaderAttributes[] = {
    {sizeof(mln_plugin_shader_attribute_v1), 0, 0, str("a_position"), MLN_PLUGIN_VERTEX_INT16_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 1, 1, str("a_radius"), MLN_PLUGIN_VERTEX_FLOAT_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 2, 2, str("a_corners"), MLN_PLUGIN_VERTEX_FLOAT_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 3, 3, str("a_rotate"), MLN_PLUGIN_VERTEX_FLOAT_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 4, 4, str("a_color_min"), MLN_PLUGIN_VERTEX_FLOAT_X4},
    {sizeof(mln_plugin_shader_attribute_v1), 5, 5, str("a_color_max"), MLN_PLUGIN_VERTEX_FLOAT_X4},
    {sizeof(mln_plugin_shader_attribute_v1), 6, 6, str("a_blur"), MLN_PLUGIN_VERTEX_FLOAT_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 7, 7, str("a_opacity"), MLN_PLUGIN_VERTEX_FLOAT_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 8, 8, str("a_stroke_width"), MLN_PLUGIN_VERTEX_FLOAT_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 9, 9, str("a_stroke_color_min"), MLN_PLUGIN_VERTEX_FLOAT_X4},
    {sizeof(mln_plugin_shader_attribute_v1), 10, 10, str("a_stroke_color_max"), MLN_PLUGIN_VERTEX_FLOAT_X4},
    {sizeof(mln_plugin_shader_attribute_v1), 11, 11, str("a_stroke_opacity"), MLN_PLUGIN_VERTEX_FLOAT_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 12, 12, str("a_translate"), MLN_PLUGIN_VERTEX_FLOAT_X4},
    {sizeof(mln_plugin_shader_attribute_v1), 13, 13, str("a_translate_anchor"), MLN_PLUGIN_VERTEX_FLOAT_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 14, 14, str("a_pitch_alignment"), MLN_PLUGIN_VERTEX_FLOAT_X2},
    {sizeof(mln_plugin_shader_attribute_v1), 15, 15, str("a_pitch_scale"), MLN_PLUGIN_VERTEX_FLOAT_X2},
};

const mln_plugin_shader_property_binding_v1 propertyBindings[] = {
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-radius"), MLN_PLUGIN_PROPERTY_ENCODING_FLOAT, 0, offsetof(DrawableUBO, radius), 1, 1, 0, offsetof(DrawableUBO, interpolation) + 0 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-corners"), MLN_PLUGIN_PROPERTY_ENCODING_FLOAT, 0, offsetof(DrawableUBO, corners), 2, 2, 0, offsetof(DrawableUBO, interpolation) + 1 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-rotate"), MLN_PLUGIN_PROPERTY_ENCODING_FLOAT, 0, offsetof(DrawableUBO, rotate), 3, 3, 0, offsetof(DrawableUBO, interpolation) + 2 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-color"), MLN_PLUGIN_PROPERTY_ENCODING_COLOR, 0, offsetof(DrawableUBO, color), 4, 5, 0, offsetof(DrawableUBO, interpolation) + 3 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-blur"), MLN_PLUGIN_PROPERTY_ENCODING_FLOAT, 0, offsetof(DrawableUBO, blur), 6, 6, 0, offsetof(DrawableUBO, interpolation) + 4 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-opacity"), MLN_PLUGIN_PROPERTY_ENCODING_FLOAT, 0, offsetof(DrawableUBO, opacity), 7, 7, 0, offsetof(DrawableUBO, interpolation) + 5 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-stroke-width"), MLN_PLUGIN_PROPERTY_ENCODING_FLOAT, 0, offsetof(DrawableUBO, stroke_width), 8, 8, 0, offsetof(DrawableUBO, interpolation) + 6 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-stroke-color"), MLN_PLUGIN_PROPERTY_ENCODING_COLOR, 0, offsetof(DrawableUBO, stroke_color), 9, 10, 0, offsetof(DrawableUBO, interpolation) + 7 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-stroke-opacity"), MLN_PLUGIN_PROPERTY_ENCODING_FLOAT, 0, offsetof(DrawableUBO, stroke_opacity), 11, 11, 0, offsetof(DrawableUBO, interpolation) + 8 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-translate"), MLN_PLUGIN_PROPERTY_ENCODING_FLOAT2, 0, offsetof(DrawableUBO, translate), 12, 12, 0, offsetof(DrawableUBO, interpolation) + 9 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-translate-anchor"), MLN_PLUGIN_PROPERTY_ENCODING_ENUM_FLOAT, 0, offsetof(DrawableUBO, translate_anchor), 13, 13, 0, offsetof(DrawableUBO, interpolation) + 10 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-pitch-alignment"), MLN_PLUGIN_PROPERTY_ENCODING_ENUM_FLOAT, 0, offsetof(DrawableUBO, pitch_alignment), 14, 14, 0, offsetof(DrawableUBO, interpolation) + 11 * sizeof(float)},
    {sizeof(mln_plugin_shader_property_binding_v1), str("ngon-pitch-scale"), MLN_PLUGIN_PROPERTY_ENCODING_ENUM_FLOAT, 0, offsetof(DrawableUBO, pitch_scale), 15, 15, 0, offsetof(DrawableUBO, interpolation) + 12 * sizeof(float)},
};
