name: MapLibre Android Bug Report
description: Report a bug you encountered with MapLibre Android.
labels: ["android"]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: MapLibre Android Version
      placeholder: e.g. 11.6.2
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android SDK Version
      placeholder: e.g. Android 10
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: "Enter the device that you encountered the issue on or enter 'Simulator' if you only see this issue in a simulator."
      placeholder: Google Pixel 7 Pro
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Explain how the issue can be reproduced.
    validations:
      required: true
  - type: dropdown
    id: renderer
    attributes:
      label: Renderer
      multiple: true
      options:
        - OpenGL (choose this if you are unsure)
        - Vulkan
      description: Mostly relevant for rendering issues.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Additional context such as screenshots or videos that are helpful.
    validations:
      required: false
