name: MapLibre iOS Bug Report
description: Report a bug you encountered with MapLibre iOS.
labels: ["ios"]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: MapLibre iOS Version
      description: MapLibre iOS Version
      placeholder: e.g. 6.8.1
    validations:
      required: true
  - type: input
    id: ios-version
    attributes:
      label: iOS Version
      description: MapLibre iOS Version
      placeholder: e.g. 6.8.1
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: device
      description: Device
      placeholder: iPhone 15 Pro
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
