load("@rules_cc//cc:defs.bzl", "cc_test")
load("//bazel:flags.bzl", "CPP_FLAGS", "MAPLIBRE_FLAGS")

cc_test(
    name = "host-tests",
    srcs = glob(["tests/*.test.cpp"]),
    copts = CPP_FLAGS + MAPLIBRE_FLAGS,
    deps = [
        "//plugins/ngon-layer",
        "@googletest//:gtest",
    ] + select({
        "@platforms//os:macos": [
            "//platform/darwin:darwin-objcpp",
            "//platform/default:mbgl-default",
            "//platform/default:standalone-layer-manager",
        ],
        "@platforms//os:linux": ["//platform/linux:impl"],
        "//conditions:default": [],
    }),
)

cc_test(
    name = "render-tests",
    timeout = "long",
    srcs = ["render_test.cpp"],
    args = [
        "--manifestPath",
        "plugins/ngon-layer/render-tests/manifest.json",
    ],
    copts = CPP_FLAGS + MAPLIBRE_FLAGS,
    data = ["//plugins/ngon-layer:render-fixtures"],
    tags = ["no-sandbox"],
    deps = [
        "//plugins/ngon-layer",
        "//render-test:render-test-srcs",
    ],
)
