load("@rules_cc//cc:defs.bzl", "cc_test")
load("//bazel:flags.bzl", "CPP_FLAGS", "MAPLIBRE_FLAGS")

cc_test(
    name = "render-tests",
    timeout = "long",
    srcs = ["render_test.cpp"],
    args = [
        "--manifestPath",
        "plugins/ngon-layer/render-tests/manifest.json",
    ],
    copts = CPP_FLAGS + MAPLIBRE_FLAGS,
    data = ["//plugins/ngon-layer:render-fixtures"],
    tags = ["no-sandbox"],
    deps = [
        "//plugins/ngon-layer",
        "//render-test:render-test-srcs",
    ],
)

cc_test(
    name = "fill-extrusion-plugin-render-tests",
    timeout = "long",
    srcs = ["fill_extrusion_plugin_render_test.cpp"],
    args = [
        "--manifestPath",
        "plugins/fill-extrusion-plugin/render-tests/manifest.json",
    ],
    copts = CPP_FLAGS + MAPLIBRE_FLAGS,
    data = ["//plugins/fill-extrusion-plugin:render-fixtures"],
    tags = ["no-sandbox"],
    deps = [
        "//plugins/fill-extrusion-plugin",
        "//render-test:render-test-srcs",
    ],
)
