name: 'save-pr-number'
description: 'Saves the current PR number as artifact'
runs:
  using: "composite"
  steps:
      - name: Save PR number
        shell: bash
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.number }}" > ./pr_number

      - name: Upload pr_number
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pr-number
          path: ./pr_number
          overwrite: true
