// Pack Metal source fragments without changing shader text or reflection data.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { deflateSync } from 'node:zlib';

export function packSources(directory) {
    const manifest = JSON.parse(fs.readFileSync(path.join(directory, 'manifest.json'), 'utf8'));
    const fragments = new Map();
    const buffers = [];
    let offset = 0;
    for (const file of [manifest.prelude, ...manifest.shaders.flatMap(s => [s.prelude, s.source])]) {
        if (fragments.has(file)) continue;
        const buffer = fs.readFileSync(path.join(directory, file));
        fragments.set(file, { offset, length: buffer.length });
        buffers.push(buffer);
        offset += buffer.length;
    }
    const source = Buffer.concat(buffers);
    return { manifest, fragments, source, compressed: deflateSync(source, { level: 9 }) };
}

export function generateCode({ manifest, fragments, source, compressed }) {
    const range = file => {
        const { offset, length } = fragments.get(file);
        return `sourceFragment(${offset}, ${length})`;
    };
    const includes = [...new Set(manifest.shaders.map(s => s.header))].sort();
    const bytes = [];
    for (let i = 0; i < compressed.length; i += 20) {
        bytes.push('    ' + [...compressed.subarray(i, i + 20)].map(b => `0x${b.toString(16).padStart(2, '0')}`).join(', ') + ',');
    }
    return `// Generated by shaders/generate_metal_shader_code.mjs. Do not edit.
// ${source.length} source bytes compressed to ${compressed.length} bytes.
// NOLINTBEGIN
#include <mln/shaders/mtl/common.hpp>
${includes.map(h => `#include <${h}>`).join('\n')}
#include <mln/util/compression.hpp>

namespace mln::shaders {
namespace {
constexpr unsigned char compressedSource[] = {
${bytes.join('\n')}
};

std::string_view sourceFragment(std::size_t offset, std::size_t length) {
    // C++ static initialization decompresses once, safely across render threads.
    // The immutable storage outlives every view returned to a shader group.
    static const std::string source = util::decompress(
        std::string(reinterpret_cast<const char*>(compressedSource), sizeof(compressedSource)));
    return std::string_view(source).substr(offset, length);
}
} // namespace

std::string_view prelude() {
    return ${range(manifest.prelude)};
}
${manifest.shaders.map(s => `
std::string_view ShaderSource<BuiltIn::${s.shader}, gfx::Backend::Type::Metal>::prelude() {
    return ${range(s.prelude)};
}

std::string_view ShaderSource<BuiltIn::${s.shader}, gfx::Backend::Type::Metal>::source() {
    return ${range(s.source)};
}
`).join('')}
} // namespace mln::shaders
// NOLINTEND
`;
}

if (process.argv[1] && fs.realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
    const { values } = parseArgs({ options: { out: { type: 'string' } } });
    const root = path.dirname(import.meta.dirname);
    const output = values.out ?? path.join(root, 'src/mln/shaders/mtl/shader_source.cpp');
    const packed = packSources(path.join(root, 'shaders/mtl'));
    fs.mkdirSync(path.dirname(output), { recursive: true });
    fs.writeFileSync(output, generateCode(packed));
    console.log(`Metal shaders: ${packed.source.length} -> ${packed.compressed.length} bytes`);
}
