// Generates backend sources from the native circle coverage/projection algorithm.
// Print to stdout for Bazel, or use --output for CMake.
import {writeFileSync} from 'node:fs';
import {parseArgs} from 'node:util';

const {values} = parseArgs({options: {output: {type: 'string'}}});

const properties = [
  ['radius', 'float', 1, 1], ['color', 'vec4', 2, 3],
  ['blur', 'float', 4, 4], ['opacity', 'float', 5, 5],
  ['stroke_width', 'float', 6, 6], ['stroke_color', 'vec4', 7, 8],
  ['stroke_opacity', 'float', 9, 9], ['translate', 'vec2', 10, 10],
  ['translate_anchor', 'enum', 11, 11], ['pitch_alignment', 'enum', 12, 12],
  ['pitch_scale', 'enum', 13, 13],
];
const drawableFields = `
    mat4 matrix;
    vec4 camera;
    vec4 view;
    vec4 interpolation0;
    vec4 interpolation1;
    vec4 interpolation2;
    vec4 interpolation3;
`;
const paintFields = `
    float radius;
    float pad0;
    float pad1;
    float blur;
    float opacity;
    float stroke_width;
    float stroke_opacity;
    float translate_anchor;
    vec4 color;
    vec4 stroke_color;
    vec2 translate;
    float pitch_alignment;
    float pitch_scale;
`;
const varyings = [['vec2', 'local'], ['vec4', 'shape'], ['vec4', 'paint'], ['vec4', 'color'], ['vec4', 'stroke_color']];
const macro = name => `MLN_PLUGIN_PROPERTY_CIRCLE_${name.toUpperCase()}_IS_UNIFORM`;
const metal = s => s.replaceAll('mat4', 'float4x4').replace(/vec([234])/g, 'float$1')
  .replaceAll('atan(', 'atan2(').replaceAll('mod(', 'fmod(');

function attributes(backend) {
  let result = backend === 'metal' ? '    short2 a_position [[attribute(0)]];\n'
    : backend === 'vulkan' ? 'layout(location = 0) in ivec2 a_position;\n' : 'in vec2 a_position;\n';
  for (const [name, type, min, max] of properties) {
    result += `#if !${macro(name)}\n`;
    const inputs = min === max ? [[name, type === 'vec2' ? 'vec4' : 'vec2', min]]
      : [[`${name}_min`, type, min], [`${name}_max`, type, max]];
    for (const [n, t, id] of inputs) {
      result += backend === 'metal' ? `    ${metal(t)} a_${n} [[attribute(${id})]];\n`
        : `${backend === 'vulkan' ? `layout(location = ${id}) ` : ''}in ${t} a_${n};\n`;
    }
    result += '#endif\n';
  }
  return result;
}

function evaluate(backend) {
  let result = '';
  properties.forEach(([name, type, min, max], i) => {
    const a = backend === 'metal' ? 'in.' : '';
    const factor = `u.interpolation${Math.floor(i / 4)}.${'xyzw'[i % 4]}`;
    const low = min !== max ? `${a}a_${name}_min` : `${a}a_${name}.${type === 'vec2' ? 'xy' : 'x'}`;
    const high = min !== max ? `${a}a_${name}_max` : `${a}a_${name}.${type === 'vec2' ? 'zw' : 'y'}`;
    result += `    ${type === 'enum' ? 'float' : type} ${name} = paint.${name};\n#if !${macro(name)}\n`;
    result += `    ${name} = ${type === 'enum' ? `${factor} < 1.0 ? ${low} : ${high}` : `mix(${low}, ${high}, ${factor})`};\n#endif\n`;
  });
  return result;
}

// Pixel coordinates have positive y downwards. Packed quad corners match CircleLayout.
const projection = `
    radius = max(radius, 0.0);
    stroke_width = max(stroke_width, 0.0);
    vec2 encoded = vec2(POSITION);
    vec2 center = floor(encoded * 0.5);
    vec2 corner = encoded - 2.0 * center;
    corner = corner * 2.0 - 1.0;
    if (translate_anchor > 0.5) {
        float c = cos(-u.view.x), s = sin(-u.view.x);
        translate = vec2(c * translate.x - s * translate.y, s * translate.x + c * translate.y);
    }
    center += translate * u.camera.z;
    vec4 projected = u.matrix * vec4(center, 0.0, 1.0);
    float outer_radius = radius + stroke_width;
    float extent = outer_radius;
    vec2 local = corner * extent;
    vec4 position;
    if (pitch_alignment < 0.5) {
        vec2 offset = local * u.camera.z;
        if (pitch_scale > 0.5) offset *= projected.w / u.camera.w;
        position = u.matrix * vec4(center + offset, 0.0, 1.0);
    } else {
        float scale = pitch_scale < 0.5 ? u.camera.w : projected.w;
        position = projected + vec4(local * u.camera.xy * scale, 0.0, 0.0);
    }
    OUT_local = corner;
    OUT_shape = vec4(radius, stroke_width, 1.0 / u.view.y / outer_radius, 0.0);
    OUT_paint = vec4(blur, opacity, stroke_opacity, 0.0);
    OUT_color = color;
    OUT_stroke_color = stroke_color;
`;

const coverage = `
    float radius = IN_shape.x;
    float stroke = IN_shape.y;
    float extrude_length = length(IN_local);
    float antialiased_blur = -max(IN_paint.x, IN_shape.z);
    float opacity_t = smoothstep(0.0, antialiased_blur, extrude_length - 1.0);
    float color_t = stroke < 0.01 ? 0.0 : smoothstep(antialiased_blur, 0.0,
        extrude_length - radius / (radius + stroke));
    vec4 result = opacity_t * mix(IN_color * IN_paint.y, IN_stroke_color * IN_paint.z, color_t);
#ifdef OVERDRAW_INSPECTOR
    result = vec4(1.0);
#endif
`;

let output = '// Generated by scripts/generate-shaders.mjs. Do not edit by hand.\n// clang-format off\n#pragma once\n\n';
const emit = (name, source) => { output += `inline constexpr char ${name}[] = R"SHADER(\n${source})SHADER";\n\n`; };
for (const backend of ['opengl', 'vulkan', 'metal']) {
  const vertexBody = evaluate(backend) + projection.replace('POSITION', backend === 'metal' ? 'in.a_position' : 'a_position')
    .replaceAll('OUT_', backend === 'metal' ? 'out.' : 'v_');
  if (backend === 'metal') {
    // Match native circle's fragment inputs: uniform paint stays in a UBO,
    // only data-driven paint consumes interpolators, and colors use half4.
    const paintProperties = properties.slice(0, 7);
    const varyingType = (name, type) => type === 'vec4' ? 'half4' : name === 'radius' ? 'float' : 'half';
    const fields = paintProperties.map(([name, type]) =>
      `#if !${macro(name)}\n    ${varyingType(name, type)} ${name};\n#endif`).join('\n');
    const assignments = paintProperties.map(([name, type]) =>
      `#if !${macro(name)}\n    out.${name} = ${varyingType(name, type)}(${name});\n#endif`).join('\n');
    const fragmentPaint = paintProperties.map(([name, type]) => {
      const t = type === 'vec4' ? 'half4' : 'float';
      return `#if ${macro(name)}\n    const ${t} ${name} = ${t}(paint.${name});\n#else\n    const ${t} ${name} = in.${name};\n#endif`;
    }).join('\n');
    const positionBody = evaluate(backend) + projection.slice(0, projection.indexOf('    OUT_local'))
      .replace('POSITION', 'in.a_position');
    const source = `struct alignas(16) CircleDrawableUBO {${metal(drawableFields)}};
struct alignas(16) CirclePaintUBO {${metal(paintFields)}};
struct CircleVertex {\n${attributes(backend)}};
struct CircleVaryings {
    float4 position [[position, invariant]];
    float2 extrude;
    float antialiasblur;
${fields}
};
vertex CircleVaryings circleVertex(CircleVertex in [[stage_in]],
    constant CircleDrawableUBO* drawables [[buffer(MLN_PLUGIN_UNIFORM_0_BINDING)]],
    constant uint& drawableIndex [[buffer(MLN_PLUGIN_DRAWABLE_INDEX_BINDING)]],
    constant CirclePaintUBO& paint [[buffer(MLN_PLUGIN_UNIFORM_1_BINDING)]]) {
    constant auto& u = drawables[drawableIndex];
    CircleVaryings out;
${metal(positionBody)}    out.position = position;
    out.extrude = corner;
    out.antialiasblur = half(1.0 / u.view.y / outer_radius);
${assignments}
    return out;
}
fragment half4 circleFragment(CircleVaryings in [[stage_in]],
    constant CirclePaintUBO& paint [[buffer(MLN_PLUGIN_UNIFORM_1_BINDING)]]) {
#ifdef OVERDRAW_INSPECTOR
    return half4(1.0);
#endif
${fragmentPaint}
    const float extrude_length = length(in.extrude);
    const float antialiased_blur = -max(blur, in.antialiasblur);
    const float opacity_t = smoothstep(0.0, antialiased_blur, extrude_length - 1.0);
    const float color_t = stroke_width < 0.01 ? 0.0 : smoothstep(antialiased_blur, 0.0,
        extrude_length - radius / (radius + stroke_width));
    return half4(opacity_t * mix(color * opacity, stroke_color * stroke_opacity, color_t));
}
`;
    emit('metalSource', source);
  } else {
    const io = direction => varyings.map(([t, n], i) => `${backend === 'vulkan' ? `layout(location = ${i}) ` : ''}${direction} ${t} v_${n};\n`).join('');
    const layout = id => backend === 'vulkan'
      ? `layout(std140, set = DRAWABLE_UBO_SET_INDEX, binding = MLN_PLUGIN_UNIFORM_${id}_BINDING)`
      : 'layout(std140)';
    emit(backend + 'Vertex', `${attributes(backend)}\n${layout(0)} uniform CircleDrawableUBO {${drawableFields}} u;
${layout(1)} uniform CirclePaintUBO {${paintFields}} paint;\n${io('out')}
void main() {
${vertexBody}    gl_Position = position;
${backend === 'vulkan' ? '    applySurfaceTransform();\n' : ''}}
`);
    emit(backend + 'Fragment', `${io('in')}${backend === 'vulkan' ? 'layout(location = 0) out vec4 fragColor;\n' : ''}
void main() {
${coverage.replaceAll('IN_', 'v_')}    fragColor = result;
}
`);
  }
}

output += 'const mln_plugin_shader_attribute_v1 shaderAttributes[] = {\n    {sizeof(mln_plugin_shader_attribute_v1), 0, 0, str("a_position"), MLN_PLUGIN_VERTEX_INT16_X2},\n';
for (const [name, type, min, max] of properties) {
  for (const [n, id] of min === max ? [[name, min]] : [[name + '_min', min], [name + '_max', max]]) {
    const size = type === 'vec4' || type === 'vec2' ? 4 : 2;
    output += `    {sizeof(mln_plugin_shader_attribute_v1), ${id}, ${id}, str("a_${n}"), MLN_PLUGIN_VERTEX_FLOAT_X${size}},\n`;
  }
}
output += '};\n\nconst mln_plugin_shader_property_binding_v1 propertyBindings[] = {\n';
properties.forEach(([name, type, min, max], i) => {
  const encoding = {float:'FLOAT',vec2:'FLOAT2',vec4:'COLOR',enum:'ENUM_FLOAT'}[type];
  output += `    {sizeof(mln_plugin_shader_property_binding_v1), str("circle-${name.replaceAll('_','-')}"), MLN_PLUGIN_PROPERTY_ENCODING_${encoding}, 1, offsetof(PaintUBO, ${name}), ${min}, ${max}, 0, offsetof(DrawableUBO, interpolation) + ${i} * sizeof(float)},\n`;
});
output += '};\n';
if (values.output) writeFileSync(values.output, output);
else process.stdout.write(output);
