if(NOT MLN_WITH_OPENGL)
    return()
endif()

message(STATUS "Configuring OpenGL ES backend")
target_compile_definitions(
        mbgl-core
        PUBLIC
        MLN_RENDER_BACKEND_OPENGL=1
        "MLN_USE_UNORDERED_DENSE=$<BOOL:${MLN_USE_UNORDERED_DENSE}>"
)
list(APPEND
        INCLUDE_FILES
        ${PROJECT_SOURCE_DIR}/include/mln/gl/renderable_resource.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/gl/renderer_backend.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/platform/gl_functions.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/shader_manifest.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/shader_group_gl.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/prelude.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/background.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/background_pattern.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/circle.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/clipping_mask.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/collision_box.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/collision_circle.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/custom_geometry.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/custom_symbol_icon.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/debug.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/fill.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/fill_outline.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/fill_pattern.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/fill_outline_pattern.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/fill_outline_triangulated.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/fill_extrusion.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/fill_extrusion_instanced.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/fill_extrusion_pattern.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/fill_extrusion_pattern_instanced.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/heatmap.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/heatmap_texture.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/hillshade_prepare.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/hillshade.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/color_relief.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/line.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/line_gradient.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/line_pattern.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/line_sdf.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/location_indicator.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/location_indicator_textured.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/raster.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/symbol_icon.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/symbol_sdf.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/symbol_text_and_icon.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/wide_vector.hpp
)
list(APPEND
        SRC_FILES
        ${PROJECT_SOURCE_DIR}/src/mln/gl/attribute.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/attribute.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/command_encoder.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/command_encoder.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/context.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/context.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/fence.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/fence.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/debugging_extension.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/debugging_extension.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/defines.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/draw_scope_resource.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/enum.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/enum.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/extension.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/framebuffer.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/index_buffer_resource.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/index_buffer_resource.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/object.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/object.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/offscreen_texture.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/offscreen_texture.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/render_pass.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/render_pass.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/renderbuffer_resource.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/renderbuffer_resource.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/renderer_backend.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/resource_pool.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/resource_pool.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/state.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/timestamp_query_extension.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/timestamp_query_extension.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/types.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/uniform.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/uniform.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/upload_pass.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/upload_pass.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/value.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/value.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/vertex_array.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/vertex_array.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/vertex_buffer_resource.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/vertex_buffer_resource.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/platform/gl_functions.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/gl/legacy/clipping_mask_program.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/gl/legacy/program_base.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/gl/legacy/program.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/gl/legacy/programs.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/gl/legacy/programs.hpp
)

list(APPEND INCLUDE_FILES
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/background_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/circle_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/collision_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/custom_drawable_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/debug_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/fill_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/fill_extrusion_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/heatmap_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/heatmap_texture_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/hillshade_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/color_relief_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/hillshade_prepare_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/line_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/location_indicator_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/raster_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/shader_defines.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/symbol_layer_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/widevector_ubo.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/style/layers/custom_drawable_layer.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/layermanager/custom_drawable_layer_factory.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/gl/shader_program_gl.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/gl/buffer_allocator.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/gl/drawable_gl.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/gl/drawable_gl_builder.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/gl/dynamic_texture.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/gl/layer_group_gl.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/gl/texture2d.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/gl/uniform_buffer_gl.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/gl/vertex_attribute_gl.hpp
)
list(APPEND SRC_FILES
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/gl/shader_info.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/gl/shader_program_gl.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/buffer_allocator.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/drawable_gl.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/drawable_gl_builder.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/drawable_gl_impl.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/dynamic_texture.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/layer_group_gl.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/texture2d.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/uniform_buffer_gl.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/gl/vertex_attribute_gl.cpp
)
