if(NOT MLN_WITH_VULKAN)
    return()
endif()

message(STATUS "Configuring Vulkan renderer backend")

target_compile_definitions(
        mbgl-core
        PUBLIC
        MLN_RENDER_BACKEND_VULKAN=1
)

list(APPEND
        INCLUDE_FILES
        ${PROJECT_SOURCE_DIR}/include/mln/style/layers/vulkan/custom_layer_init_parameters.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/style/layers/vulkan/custom_layer_render_parameters.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/buffer_resource.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/command_encoder.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/context.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/drawable.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/descriptor_set.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/drawable_builder.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/dynamic_texture.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/index_buffer_resource.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/layer_group.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/offscreen_texture.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/pipeline.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/renderer_backend.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/render_pass.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/renderable_resource.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/texture2d.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/tile_layer_group.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/uniform_buffer.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/upload_pass.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/vertex_attribute.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/vulkan/vertex_buffer_resource.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/shader_group.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/shader_program.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/background.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/circle.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/clipping_mask.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/collision.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/common.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/custom_geometry.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/custom_symbol_icon.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/fill.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/fill_extrusion.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/fill_extrusion_shadow.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/heatmap.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/heatmap_texture.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/hillshade.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/hillshade_prepare.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/color_relief.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/line.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/location_indicator.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/raster.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/symbol.hpp
        ${PROJECT_SOURCE_DIR}/include/mln/shaders/vulkan/widevector.hpp
)

list(APPEND
        SRC_FILES
        ${PROJECT_SOURCE_DIR}/src/mln/style/layers/vulkan/custom_layer_render_parameters.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/buffer_resource.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/command_encoder.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/context.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/descriptor_set.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/drawable.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/drawable_builder.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/drawable_impl.hpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/dynamic_texture.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/index_buffer_resource.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/layer_group.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/offscreen_texture.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/pipeline.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/renderer_backend.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/render_pass.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/renderable_resource.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/texture2d.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/tile_layer_group.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/uniform_buffer.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/upload_pass.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/vertex_attribute.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/vulkan/vertex_buffer_resource.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/shader_program.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/background.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/circle.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/clipping_mask.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/collision.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/custom_geometry.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/custom_symbol_icon.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/debug.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/fill.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/fill_extrusion.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/fill_extrusion_shadow.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/heatmap.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/heatmap_texture.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/hillshade.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/hillshade_prepare.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/color_relief.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/line.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/location_indicator.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/raster.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/symbol.cpp
        ${PROJECT_SOURCE_DIR}/src/mln/shaders/vulkan/widevector.cpp
)
