name: android-base-docker-image
on:
  workflow_dispatch
jobs:
  push_to_registry:
    name: Docker image android-base
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push android-base image
        uses: docker/build-push-action@v3
        with:
          file: ./platform/android/docker/android-base        
          context: ./platform/android/docker
          tags: ghcr.io/maplibre/android-base:latest
          push: true