name: gh-pages-mdbook

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/mdbook/**'
  push:
    branches:
      - main
    paths:
      - 'docs/mdbook/**'

jobs:
  gh-pages-mdbook-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@ee69d230fe19748b7abf22df32acaa93833fad08 # v2.0.0
      - name: Install Dependencies
        shell: bash
        run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
      - name: Install mdbook-mermaid
        run: cargo install mdbook-mermaid
      - name: Build
        working-directory: docs/mdbook
        shell: bash
        run: mdbook build
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: book
          path: docs/mdbook/book/

  gh-pages-mdbook-deploy:
    needs: gh-pages-mdbook-build
    if: github.event_name != 'pull_request'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - name: Download book
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v4
        with:
          name: book
          path: artifacts/book

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: artifacts/book
          target-folder: docs/book
