name: gh-pages-android-api

on:
  workflow_dispatch:
  workflow_run:
    workflows: [android-release]
    types:
      - completed

jobs:
  gh-pages-android-api:
    defaults:
      run:
        working-directory: platform/android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Generate documentation
        run: ./gradlew dokkaGenerate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: platform/android/MapLibreAndroid/build/dokka/html
          target-folder: android/api/
