name: macos-release

on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: macos-10.15
    env:
      BUILDTYPE: Release
      SYMBOLS: NO
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      CILAUNCH: true
    defaults:
      run:
        working-directory: platform/ios
        shell: bash 

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install macos dependencies
        run: |
          brew list cmake || brew install cmake
          brew list ccache || brew install ccache
          brew list pkg-config || brew install pkg-config
          brew list glfw3 || brew install glfw3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: npm install
        run: npm install --ignore-scripts          

      - name: Prepare ccache
        run: ccache --clear       

      - name: Cache ccache
        uses: actions/cache@v3
        env:
          cache-name: ccache-v1     
        with:
          path: ~/.ccache'
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}-${{ github.head_ref }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}
            ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}-${{ github.ref }}
            ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}  

      - name: Clear ccache statistics
        run: |
          ccache --zero-stats
          ccache --max-size=2G
          ccache --show-stats            

      - name: Install packaging dependencies
        run: |
          ./platform/ios/scripts/install-packaging-dependencies.sh

      - name: Build package
        run: make xpackage
                
      - name: Deploy package
        run: make xdeploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
