name: macos-webgpu-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'cmake/**'
      - '.github/workflows/macos-webgpu-ci.yml'
      - 'platform/darwin/**'
      - 'platform/macos/**'
      - 'platform/glfw/**'
      - 'platform/default/**'
      - 'render-test/**'
      - 'src/**'
      - 'include/**'
      - 'vendor/**'
      - 'metrics/**'
      - '.gitmodules'
      - '!**/*.md'
  pull_request:
    branches:
      - main
    paths:
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'cmake/**'
      - '.github/workflows/macos-webgpu-ci.yml'
      - 'platform/darwin/**'
      - 'platform/macos/**'
      - 'platform/glfw/**'
      - 'platform/default/**'
      - 'render-test/**'
      - 'src/**'
      - 'include/**'
      - 'vendor/**'
      - 'metrics/**'
      - '.gitmodules'
      - '!**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  webgpu:
    name: macOS WebGPU CI Tests
    runs-on: macos-14

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install dependencies
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        run: |
          brew install cmake ninja pkg-config python@3.11 go glfw libuv icu4c jpeg-turbo webp libpng ccache
          brew link --overwrite python@3.11

      - name: Configure environment
        run: |
          {
            echo "PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig:$(brew --prefix libuv)/lib/pkgconfig:${PKG_CONFIG_PATH}"
            echo "PATH=$(brew --prefix python@3.11)/bin:$(brew --prefix go)/bin:$PATH"
            echo "CC=clang"
            echo "CXX=clang++"
          } >> "$GITHUB_ENV"

      - name: Configure build
        run: cmake --preset macos-webgpu

      - name: Build targets
        run: |
          cmake --build build-macos-webgpu --target \
            mbgl-render-test-runner

      - name: Prepare render test output directory
        run: mkdir -p metrics/macos-webgpu

      - name: Run WebGPU render tests
        id: render_test
        run: build-macos-webgpu/mbgl-render-test-runner --manifestPath metrics/macos-webgpu.json

      - name: Upload render report
        if: always() && steps.render_test.outcome == 'failure'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: macos-webgpu-render-report
          path: metrics/macos-webgpu.html
