name: Pin GitHub Actions to SHAs
on:
  pull_request:
    paths:
      - .github/**
permissions:
  contents: write
jobs:
  pinact:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Check if all actions versions are immutable SHAs
        uses: suzuki-shunsuke/pinact-action@d735505f3decf76fca3fdbb4c952e5b3eba0ffdd # v0.1.2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
